---
language: java
dist: focal

services:
  - docker

jdk:
  - openjdk8
  - openjdk11
  - openjdk17

notifications:
  email: true

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"
    - SERVER_AUTH_TYPE=basic SERVER_URL=http://127.0.0.1:5984 SERVER_USERNAME=admin SERVER_PASSWORD=password

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"


before_install:
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x
- bash scripts/setup_couch.sh

before_script:
- echo "TRAVIS_TAG = '${TRAVIS_TAG}'"
- >-
      [ -n "${TRAVIS_TAG}" ]
      && mvn versions:set -DnewVersion=${TRAVIS_TAG} -DgenerateBackupPoms=false
      || true

script:
- mvn clean verify $MVN_ARGS

# To enable semantic-release, uncomment these sections.
# before_deploy:
# - pip install --user bump2version
# - npm install @semantic-release/changelog
# - npm install @semantic-release/exec
# - npm install @semantic-release/git
# - npm install @semantic-release/github
#
# deploy:
#   # On master, run semrel to create a new tagged-release.
#   - provider: script
#     script: npx semantic-release
#     skip_cleanup: true
#     on:
#       branch: master
#   # Publish jars on bintray for a tagged release.
#   - provider: script
#     script: "mvn deploy $MVN_ARGS -DskipTests"
#     skip_cleanup: true
#     on:
#       tags: true
#       jdk: openjdk8
#   # Publish javadocs to gh-pages only for a tagged-release.
#   - provider: script
#     script: "./build/publish-javadoc.sh"
#     skip_cleanup: true
#     on:
#       tags: true
#       jdk: openjdk8
#   # Upload code coverage reports to codecov.io for master or tagged release
#   - provider: script
#     script: $HOME/codecov-bash.sh -s modules/coverage-reports/target/site/jacoco-aggregate -t $CODECOV_TOKEN
#     skip_cleanup: true
#     on:
#       condition: $TRAVIS_BRANCH == master || -n "$TRAVIS_TAG"
#       jdk: openjdk8
