name: docs
on:
  pull_request:
    branches: ['main']
permissions: {}
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup java 25
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        distribution: 'semeru'
        java-version: '25'
        cache: 'maven'
        check-latest: false
    - name: Build docs
      run: mvn javadoc:aggregate
